//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.8.2
//     from Assets/Input/PannableCameraControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;
using UnityEngine;

public partial class @PannableCameraControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PannableCameraControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PannableCameraControls"",
    ""maps"": [
        {
            ""name"": ""PlanetaryMap"",
            ""id"": ""677ee709-e217-44eb-93ad-4480a4982674"",
            ""actions"": [
                {
                    ""name"": ""TimeSpeed1"",
                    ""type"": ""Button"",
                    ""id"": ""7dbcabf3-180a-4fbe-9840-2d4a67efde2a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed2"",
                    ""type"": ""Button"",
                    ""id"": ""7f5b8845-6062-4d57-88ae-9a7ff616ba99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed3"",
                    ""type"": ""Button"",
                    ""id"": ""523ba18f-4b7a-4dde-9b71-f7c00be74740"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed4"",
                    ""type"": ""Button"",
                    ""id"": ""1de3165d-2518-4ce6-bf39-810d09955fa3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed5"",
                    ""type"": ""Button"",
                    ""id"": ""cbc7be8f-c5c4-46bf-b71b-347dcea9d27d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed6"",
                    ""type"": ""Button"",
                    ""id"": ""3c54f0ae-d28d-4905-b9a0-f5465d2a2920"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeed7"",
                    ""type"": ""Button"",
                    ""id"": ""1419f097-6217-496f-826e-a901e9e3ece3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TimeSpeedPauseToggle"",
                    ""type"": ""Button"",
                    ""id"": ""b7e1a580-3e43-4fea-a71f-6cc8ac1c313c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pan"",
                    ""type"": ""Value"",
                    ""id"": ""458e8f13-5cae-434b-a9f6-7220f673b2b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraOrbit"",
                    ""type"": ""Value"",
                    ""id"": ""c97d45db-b8a5-43d0-8119-45eda8df6471"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraOrbitActivation"",
                    ""type"": ""Button"",
                    ""id"": ""f7e63b69-d44d-4a59-9fdc-5402643956ba"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CameraZoom"",
                    ""type"": ""Value"",
                    ""id"": ""10c6c403-1693-42f3-ace2-2bc074c6fb12"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""941c926e-1ef4-4c95-a49a-ad176a0dba43"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42d03148-7ee8-45ae-880e-542a3cdc7877"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d413bda5-5b93-410f-bc83-a3376473c420"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78503e08-f1ea-4a45-92b2-6509c14a8699"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ca917422-fb2a-43e9-8d7b-feda257f993d"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""db202ceb-b1d9-4313-bed2-03dc846675ec"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b1bb51f-d18c-495c-afd3-ddf428a45c91"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeedPauseToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c47deb4-d914-4dd2-9c92-4da182b132f8"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""TimeSpeed7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""8edb56e5-e0c5-4d4d-b27a-1e7714153aa2"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""0ffa727a-4129-4b91-9116-58670fa62467"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""9a8b61c5-2064-49f6-9ab1-ade276266160"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""d2385568-5de1-46cc-8be3-21547cd76e2d"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""d71d4657-8c68-4698-ae0c-8154fd234569"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""9eea7bae-10e5-4257-b14c-5f23581f20a1"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pan"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""a4af539d-74ac-4282-9c99-dc55e9f51e5e"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""92ad50e5-133b-468f-b233-df8a22cdc583"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5e59619a-4452-41da-804b-d1a0c02d5480"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""072394e6-7b71-4f08-ac6b-f1542ada24ad"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""Pan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8ec1d265-6d01-424e-8570-ff98eb744e3c"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""CameraOrbit"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""863deef0-0e4f-40e3-9ab1-8d8e51451d80"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""CameraOrbitActivation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""12a28ce2-e929-4544-a9fb-62292d1e5add"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KeyboardMouse"",
                    ""action"": ""CameraZoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KeyboardMouse"",
            ""bindingGroup"": ""KeyboardMouse"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // PlanetaryMap
        m_PlanetaryMap = asset.FindActionMap("PlanetaryMap", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed1 = m_PlanetaryMap.FindAction("TimeSpeed1", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed2 = m_PlanetaryMap.FindAction("TimeSpeed2", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed3 = m_PlanetaryMap.FindAction("TimeSpeed3", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed4 = m_PlanetaryMap.FindAction("TimeSpeed4", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed5 = m_PlanetaryMap.FindAction("TimeSpeed5", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed6 = m_PlanetaryMap.FindAction("TimeSpeed6", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeed7 = m_PlanetaryMap.FindAction("TimeSpeed7", throwIfNotFound: true);
        m_PlanetaryMap_TimeSpeedPauseToggle = m_PlanetaryMap.FindAction("TimeSpeedPauseToggle", throwIfNotFound: true);
        m_PlanetaryMap_Pan = m_PlanetaryMap.FindAction("Pan", throwIfNotFound: true);
        m_PlanetaryMap_CameraOrbit = m_PlanetaryMap.FindAction("CameraOrbit", throwIfNotFound: true);
        m_PlanetaryMap_CameraOrbitActivation = m_PlanetaryMap.FindAction("CameraOrbitActivation", throwIfNotFound: true);
        m_PlanetaryMap_CameraZoom = m_PlanetaryMap.FindAction("CameraZoom", throwIfNotFound: true);
    }

    ~@PannableCameraControls()
    {
        Debug.Assert(!m_PlanetaryMap.enabled, "This will cause a leak and performance issues, PannableCameraControls.PlanetaryMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlanetaryMap
    private readonly InputActionMap m_PlanetaryMap;
    private List<IPlanetaryMapActions> m_PlanetaryMapActionsCallbackInterfaces = new List<IPlanetaryMapActions>();
    private readonly InputAction m_PlanetaryMap_TimeSpeed1;
    private readonly InputAction m_PlanetaryMap_TimeSpeed2;
    private readonly InputAction m_PlanetaryMap_TimeSpeed3;
    private readonly InputAction m_PlanetaryMap_TimeSpeed4;
    private readonly InputAction m_PlanetaryMap_TimeSpeed5;
    private readonly InputAction m_PlanetaryMap_TimeSpeed6;
    private readonly InputAction m_PlanetaryMap_TimeSpeed7;
    private readonly InputAction m_PlanetaryMap_TimeSpeedPauseToggle;
    private readonly InputAction m_PlanetaryMap_Pan;
    private readonly InputAction m_PlanetaryMap_CameraOrbit;
    private readonly InputAction m_PlanetaryMap_CameraOrbitActivation;
    private readonly InputAction m_PlanetaryMap_CameraZoom;
    public struct PlanetaryMapActions
    {
        private @PannableCameraControls m_Wrapper;
        public PlanetaryMapActions(@PannableCameraControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @TimeSpeed1 => m_Wrapper.m_PlanetaryMap_TimeSpeed1;
        public InputAction @TimeSpeed2 => m_Wrapper.m_PlanetaryMap_TimeSpeed2;
        public InputAction @TimeSpeed3 => m_Wrapper.m_PlanetaryMap_TimeSpeed3;
        public InputAction @TimeSpeed4 => m_Wrapper.m_PlanetaryMap_TimeSpeed4;
        public InputAction @TimeSpeed5 => m_Wrapper.m_PlanetaryMap_TimeSpeed5;
        public InputAction @TimeSpeed6 => m_Wrapper.m_PlanetaryMap_TimeSpeed6;
        public InputAction @TimeSpeed7 => m_Wrapper.m_PlanetaryMap_TimeSpeed7;
        public InputAction @TimeSpeedPauseToggle => m_Wrapper.m_PlanetaryMap_TimeSpeedPauseToggle;
        public InputAction @Pan => m_Wrapper.m_PlanetaryMap_Pan;
        public InputAction @CameraOrbit => m_Wrapper.m_PlanetaryMap_CameraOrbit;
        public InputAction @CameraOrbitActivation => m_Wrapper.m_PlanetaryMap_CameraOrbitActivation;
        public InputAction @CameraZoom => m_Wrapper.m_PlanetaryMap_CameraZoom;
        public InputActionMap Get() { return m_Wrapper.m_PlanetaryMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlanetaryMapActions set) { return set.Get(); }
        public void AddCallbacks(IPlanetaryMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlanetaryMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlanetaryMapActionsCallbackInterfaces.Add(instance);
            @TimeSpeed1.started += instance.OnTimeSpeed1;
            @TimeSpeed1.performed += instance.OnTimeSpeed1;
            @TimeSpeed1.canceled += instance.OnTimeSpeed1;
            @TimeSpeed2.started += instance.OnTimeSpeed2;
            @TimeSpeed2.performed += instance.OnTimeSpeed2;
            @TimeSpeed2.canceled += instance.OnTimeSpeed2;
            @TimeSpeed3.started += instance.OnTimeSpeed3;
            @TimeSpeed3.performed += instance.OnTimeSpeed3;
            @TimeSpeed3.canceled += instance.OnTimeSpeed3;
            @TimeSpeed4.started += instance.OnTimeSpeed4;
            @TimeSpeed4.performed += instance.OnTimeSpeed4;
            @TimeSpeed4.canceled += instance.OnTimeSpeed4;
            @TimeSpeed5.started += instance.OnTimeSpeed5;
            @TimeSpeed5.performed += instance.OnTimeSpeed5;
            @TimeSpeed5.canceled += instance.OnTimeSpeed5;
            @TimeSpeed6.started += instance.OnTimeSpeed6;
            @TimeSpeed6.performed += instance.OnTimeSpeed6;
            @TimeSpeed6.canceled += instance.OnTimeSpeed6;
            @TimeSpeed7.started += instance.OnTimeSpeed7;
            @TimeSpeed7.performed += instance.OnTimeSpeed7;
            @TimeSpeed7.canceled += instance.OnTimeSpeed7;
            @TimeSpeedPauseToggle.started += instance.OnTimeSpeedPauseToggle;
            @TimeSpeedPauseToggle.performed += instance.OnTimeSpeedPauseToggle;
            @TimeSpeedPauseToggle.canceled += instance.OnTimeSpeedPauseToggle;
            @Pan.started += instance.OnPan;
            @Pan.performed += instance.OnPan;
            @Pan.canceled += instance.OnPan;
            @CameraOrbit.started += instance.OnCameraOrbit;
            @CameraOrbit.performed += instance.OnCameraOrbit;
            @CameraOrbit.canceled += instance.OnCameraOrbit;
            @CameraOrbitActivation.started += instance.OnCameraOrbitActivation;
            @CameraOrbitActivation.performed += instance.OnCameraOrbitActivation;
            @CameraOrbitActivation.canceled += instance.OnCameraOrbitActivation;
            @CameraZoom.started += instance.OnCameraZoom;
            @CameraZoom.performed += instance.OnCameraZoom;
            @CameraZoom.canceled += instance.OnCameraZoom;
        }

        private void UnregisterCallbacks(IPlanetaryMapActions instance)
        {
            @TimeSpeed1.started -= instance.OnTimeSpeed1;
            @TimeSpeed1.performed -= instance.OnTimeSpeed1;
            @TimeSpeed1.canceled -= instance.OnTimeSpeed1;
            @TimeSpeed2.started -= instance.OnTimeSpeed2;
            @TimeSpeed2.performed -= instance.OnTimeSpeed2;
            @TimeSpeed2.canceled -= instance.OnTimeSpeed2;
            @TimeSpeed3.started -= instance.OnTimeSpeed3;
            @TimeSpeed3.performed -= instance.OnTimeSpeed3;
            @TimeSpeed3.canceled -= instance.OnTimeSpeed3;
            @TimeSpeed4.started -= instance.OnTimeSpeed4;
            @TimeSpeed4.performed -= instance.OnTimeSpeed4;
            @TimeSpeed4.canceled -= instance.OnTimeSpeed4;
            @TimeSpeed5.started -= instance.OnTimeSpeed5;
            @TimeSpeed5.performed -= instance.OnTimeSpeed5;
            @TimeSpeed5.canceled -= instance.OnTimeSpeed5;
            @TimeSpeed6.started -= instance.OnTimeSpeed6;
            @TimeSpeed6.performed -= instance.OnTimeSpeed6;
            @TimeSpeed6.canceled -= instance.OnTimeSpeed6;
            @TimeSpeed7.started -= instance.OnTimeSpeed7;
            @TimeSpeed7.performed -= instance.OnTimeSpeed7;
            @TimeSpeed7.canceled -= instance.OnTimeSpeed7;
            @TimeSpeedPauseToggle.started -= instance.OnTimeSpeedPauseToggle;
            @TimeSpeedPauseToggle.performed -= instance.OnTimeSpeedPauseToggle;
            @TimeSpeedPauseToggle.canceled -= instance.OnTimeSpeedPauseToggle;
            @Pan.started -= instance.OnPan;
            @Pan.performed -= instance.OnPan;
            @Pan.canceled -= instance.OnPan;
            @CameraOrbit.started -= instance.OnCameraOrbit;
            @CameraOrbit.performed -= instance.OnCameraOrbit;
            @CameraOrbit.canceled -= instance.OnCameraOrbit;
            @CameraOrbitActivation.started -= instance.OnCameraOrbitActivation;
            @CameraOrbitActivation.performed -= instance.OnCameraOrbitActivation;
            @CameraOrbitActivation.canceled -= instance.OnCameraOrbitActivation;
            @CameraZoom.started -= instance.OnCameraZoom;
            @CameraZoom.performed -= instance.OnCameraZoom;
            @CameraZoom.canceled -= instance.OnCameraZoom;
        }

        public void RemoveCallbacks(IPlanetaryMapActions instance)
        {
            if (m_Wrapper.m_PlanetaryMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlanetaryMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlanetaryMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlanetaryMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlanetaryMapActions @PlanetaryMap => new PlanetaryMapActions(this);
    private int m_KeyboardMouseSchemeIndex = -1;
    public InputControlScheme KeyboardMouseScheme
    {
        get
        {
            if (m_KeyboardMouseSchemeIndex == -1) m_KeyboardMouseSchemeIndex = asset.FindControlSchemeIndex("KeyboardMouse");
            return asset.controlSchemes[m_KeyboardMouseSchemeIndex];
        }
    }
    public interface IPlanetaryMapActions
    {
        void OnTimeSpeed1(InputAction.CallbackContext context);
        void OnTimeSpeed2(InputAction.CallbackContext context);
        void OnTimeSpeed3(InputAction.CallbackContext context);
        void OnTimeSpeed4(InputAction.CallbackContext context);
        void OnTimeSpeed5(InputAction.CallbackContext context);
        void OnTimeSpeed6(InputAction.CallbackContext context);
        void OnTimeSpeed7(InputAction.CallbackContext context);
        void OnTimeSpeedPauseToggle(InputAction.CallbackContext context);
        void OnPan(InputAction.CallbackContext context);
        void OnCameraOrbit(InputAction.CallbackContext context);
        void OnCameraOrbitActivation(InputAction.CallbackContext context);
        void OnCameraZoom(InputAction.CallbackContext context);
    }
}
